### ISSUE TITLE
Support for Specifying a Seed

### ISSUE THREAD

**Issue by sebasptsch** [jacksalici/emoji-helper#1]
Hi there, I've just started using this package in my project and was wondering if it would be possible to specify a seed in the emoji.random() function as an optional argument?

Thanks!

**Comment by jacksalici** [comment]
Hello, thank you for your suggestion. I appreciated it very much. Currently, the seed is not supported yet, as you probably have seen. However, I can implement it in the next few days and then release an update.  I leave this issue open so that I can update you as soon as I will develop the feature.

**Comment by sebasptsch** [comment]
Thanks for your work!
